name: Build PH MUSIC PLAY APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Extrair projeto
        run: |
          unzip -q PHMusicPlay_GitHub_Build.zip
          find . -maxdepth 4 -type f | head -50

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Compilar APK
        working-directory: phproj/PHMusicPlay
        run: gradle assembleDebug --no-daemon

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: PH-MUSIC-PLAY-APK
          path: phproj/PHMusicPlay/app/build/outputs/apk/debug/app-debug.apk
