name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew

      - name: Gerar APK
        run: ./gradlew assembleDebug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: PHMusicPlay-APK
          path: '**/build/outputs/apk/**/*.apk'
